Repository PIM-PillReminder/PIM, pull requests merged in 2023-12, with the labels that each got.

#30 27 feat custom watch alert watchos
  PIM/.DS_Store
  PIM/PIM.xcodeproj/project.pbxproj
  PIM/PIM.xcodeproj/project.xcworkspace/xcuserdata/sinjeong-yeon.xcuserdatad/UserInterfaceState.xcuserstate
  PIM/PIM.xcodeproj/xcuserdata/sinjeong-yeon.xcuserdatad/xcschemes/xcschememanagement.plist
  PIM/PIM/PIMApp.swift
  PIM/PIM/View/MainView.swift
  PIM/PIM/View/Onboarding/OnboardingMainView.swift
  PIM/PIM_watch Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  PIM/PIM_watch Watch App/Assets.xcassets/AppIcon.appiconset/1024.png
  PIM/PIM_watch Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  PIM/PIM_watch Watch App/Assets.xcassets/Contents.json
  PIM/PIM_watch Watch App/Assets.xcassets/happyPimi.imageset/Contents.json
  PIM/PIM_watch Watch App/Assets.xcassets/happyPimi.imageset/happyPimi.svg
  PIM/PIM_watch Watch App/Assets.xcassets/sadPimi.imageset/Contents.json
  PIM/PIM_watch Watch App/Assets.xcassets/sadPimi.imageset/sadPimi.svg
  PIM/PIM_watch Watch App/ContentView.swift
  PIM/PIM_watch Watch App/Font/Pretendard-Bold.ttf
  PIM/PIM_watch Watch App/Font/Pretendard-ExtraBold.ttf
  PIM/PIM_watch Watch App/Font/Pretendard-ExtraLight.ttf
  PIM/PIM_watch Watch App/Font/Pretendard-Light.ttf
  PIM/PIM_watch Watch App/Font/Pretendard-Medium.ttf
  PIM/PIM_watch Watch App/Font/Pretendard-Regular.ttf
  PIM/PIM_watch Watch App/Font/Pretendard-SemiBold.ttf
  PIM/PIM_watch Watch App/Font/Pretendard-Thin.ttf
  PIM/PIM_watch Watch App/PIM_watchApp.swift
  PIM/PIM_watch Watch App/Preview Content/Preview Assets.xcassets/Contents.json
  PIM/PIM_watch Watch App/WatchButtonStyle.swift
  PIM/PIM_watch Watch App/WatchColorExtension.swift
  PIM/PIM_watch Watch App/WatchFontExtension.swift
Labels: 💻 feat

#29 [🐛] 기존 알림 삭제 로직 추가
  .gitignore
  PIM/.DS_Store
  PIM/PIM.xcodeproj/project.xcworkspace/xcuserdata/sinjeong-yeon.xcuserdatad/UserInterfaceState.xcuserstate
  PIM/PIM/LocalNotificationManager.swift
Labels: 🐛 bug

#33 25 fix details
  PIM/PIM/PIMApp.swift
  PIM/PIM/Settings/PIMCustomSlider.swift
  PIM/PIM/Settings/SettingNotiVIew.swift
  PIM/PIM/Settings/SettingView.swift
  PIM/PIM/Settings/SettingViewModel.swift
  PIM/PIM/Settings/TimePickerView.swift
  PIM/PIM/View/Onboarding/OnboardingView4.swift
Labels: 🐛 bug, 💻 feat

#41 [feat] - 모달 타이틀 추가
  PIM/PIM/PIMApp.swift
  PIM/PIM/View/Settings/SettingNotiVIew.swift
  PIM/PIM/View/Settings/TimePickerView.swift
Labels: 💻 feat
